# Generated by Django 5.1.3 on 2025-07-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employerprofile_company_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='profile_picture',
            new_name='company_logo',
        ),
    ]
