# Generated by Django 5.1.3 on 2025-07-14 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_employerprofile_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('pune', 'Pune'), ('mumbai', 'Mumbai'), ('delhi', 'Delhi'), ('hyderabad', 'Hyderabad'), ('bangalore', 'Bangalore'), ('chennai', 'Chennai'), ('noida', 'Noida'), ('gurgaon', 'Gurgaon'), ('vizag', 'Vizag'), ('remote', 'Remote')], max_length=255)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], max_length=20)),
                ('salary', models.PositiveIntegerField()),
                ('experience_required', models.CharField(max_length=100)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('experience', models.CharField(choices=[('fresher', 'Fresher'), ('1-3', '1-3 years'), ('4-6', '4-6 years'), ('7-10', '7-10 years'), ('10+', '10+ years')], max_length=50)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='applications/')),
                ('cover_letter', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobseekerprofile')),
            ],
        ),
    ]
