# Generated by Django 5.1.3 on 2025-07-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_job_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.CharField(choices=[('fresher', 'Fresher'), ('1-3', '1-3 years'), ('4-6', '4-6 years'), ('7-10', '7-10 years'), ('10+', '10+ years')], max_length=100),
        ),
    ]
