# Generated by Django 5.1.3 on 2025-07-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_job_experience_alter_job_experience_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='industry',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
