# Generated by Django 5.1.3 on 2025-07-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_employerprofile_company_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='applications/resumes/'),
        ),
    ]
