# Generated by Django 5.1.3 on 2025-07-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_work_mode',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], max_length=20),
        ),
    ]
