# Generated by Django 5.1.3 on 2025-07-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_jobseekerprofile_preferred_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51-200', '51-200 Employees'), ('201-500', '201-500 Employees'), ('500+', '500+ Employees')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
