# Generated by Django 5.1.3 on 2025-07-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_employerprofile_company_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.CharField(choices=[('fresher', 'Fresher'), ('1-3', '1 to 3 Years'), ('4-6', '4 to 6 Years'), ('7-10', '7 to 10 Years'), ('10+', '10+ Years')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Hyderabad', 'Hyderabad'), ('Bangalore', 'Bangalore'), ('Chennai', 'Chennai'), ('Noida', 'Noida'), ('Gurgaon', 'Gurgaon'), ('Vizag', 'Vizag'), ('Remote', 'Remote')], max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='applications/cover_letters/'),
        ),
    ]
