# Generated by Django 5.1.3 on 2025-07-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_job_experience_required_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('pune', 'Pune'), ('mumbai', 'Mumbai'), ('delhi', 'Delhi'), ('hyderabad', 'Hyderabad'), ('bangalore', 'Bangalore'), ('chennai', 'Chennai'), ('noida', 'Noida'), ('gurgaon', 'Gurgaon'), ('vizag', 'Vizag'), ('remote', 'Remote')], max_length=255),
        ),
    ]
